version: "3.9"

services:
  backend_node:
    container_name: backend_node
    build:
      context: "./backend"
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - "8080:8080"
      - "9229:9229"
    depends_on:
      - postgres
      #   - redis
  postgres:
    container_name: db-postgres
    # image: "postgres:15.4-alpine"
    image: "ankane/pgvector" # This docker image with postgres@15.4
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db-demo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # redis:
  #   container_name: redis
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
volumes:
  postgres_data:
